base:
  templates: .temples
  target: src

regex:
  js: '\/\/ temples: (.+)'

generators:
  component:
    doc: React component

    props:
      - name: name
        doc: component name

    files:
      - template: component.hbs
        target: 'components/{{ title-case name }}/index.js'
      - template: styles.hbs
        target: 'components/{{ title-case name }}/styles.module.scss'

    inserts:
      - target: components/index.js

  page:
    doc: Next page component

    props:
      - name: name
        doc: page component name

    files:
      - template: page.hbs
        target: 'pages/{{ kebab-case name }}.js'
      - template: styles.hbs
        target: 'pages/styles/{{ kebab-case name }}.module.scss'
